### ISSUE TITLE
Blood Type screen - 'back' button

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/MobileClient#25]
On the **"Blood type" screen** it would be useful to add a **"back" button**.  
It's difficult to exit from Blood Type screen to user details.

Unable to go to menu via menu bar - unable to click (on the picture)

@s20383 Aleksandra Mira

![bloodtypescreen](https://user-images.githubusercontent.com/80711769/168026812-591315db-93dd-4b49-a1a3-4e52a901c383.PNG)

**Comment by s20383** [comment]
Solved
