### ISSUE TITLE
Edit Account Screen - password validation, calendar

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/MobileClient#26]
On the **'Edit Acount' screen** it would be useful to add the option to select your birth date from the calendar.
(small suggestion) You can also take care of password validation - checking if the old password is not the same as the new one.

@s20383 Aleksandra Mira

![Edit Account](https://user-images.githubusercontent.com/80711769/168028039-912e2729-5007-4547-b805-f50e898aa588.PNG)

**Comment by s20383** [comment]
++ Retype new password
