### ISSUE TITLE
'Map' button issue

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/MobileClient#43]
Unable to interact with the **'Map' button** in the sidebar. The application crashes during this action. 

![panel](https://user-images.githubusercontent.com/80711769/175111648-8eb49adb-18ab-4c5c-ae67-a89ab83cc11d.PNG)

Errors in attachment.

![fff](https://user-images.githubusercontent.com/80711769/175111695-73cc26ae-6132-4143-8880-df07fdccc266.PNG)

@s20610

**Comment by s20610** [comment]
Last commit fixed the issue
