### ISSUE TITLE
[PARAMEDIC] The panel (in 'support', 'victim', 'equipment') doesn't work

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/MobileClient#53]
Panel with tabs 'victim', 'support', 'equipment' works only on the main screen (ambulance shifts). 
After switching from the main screen, e.g. to the 'call for support' view, you can't go to the 'victim' or 'equpiment'.

https://user-images.githubusercontent.com/80711769/180175576-f87d72c0-b232-4521-b88c-ca858bd38236.mp4

@s20610

**Comment by s20383** [comment]
solved
