### ISSUE TITLE
[SUGGESTION] [PARAMEDIC] Summary in 'Call for support' 

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/MobileClient#55]
If we choose more than one option in 'Call for support', instead of displaying one part of information, e.g. "Police", you can add a summary of what services have been added.

https://user-images.githubusercontent.com/80711769/180176675-9ed690f1-5609-4bb9-a928-1ad007136536.mp4

@s20610

**Comment by s20383** [comment]
![image](https://user-images.githubusercontent.com/80422818/182675702-1add7701-1744-41d5-823e-46c4054e8086.png)
